name: zaigoecommerce
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  http: ^0.13.5
  fluttertoast: ^8.0.9
  flutter_rating_stars: ^1.0.3+4
  url_launcher: ^6.1.5
  path_provider: ^2.0.9
  image_picker: ^0.8.5
  google_maps_flutter: ^2.1.7
  geolocator: ^9.0.1
  geocoding: ^2.0.4
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.3+2

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - asset/images/Screenshot from 2022-08-17 17-31-22.png

